### PR TITLE
Add Carol King to BANDS

### PR DESCRIPTION
**Pull request by jakeboxer**
https://twitter.com/chillsitch/status/492330131759710208

### CODE REVIEW

**Comment by chillsitch** [comment]
I can't merge this. You mind rebasing?

your rebase belongs to us ;)

**Comment by jakeboxer** [comment]
:+1:

**Comment by chillsitch** [comment]
Closing in favor of https://github.com/chillsitch/chill-sitch/pull/3. 

it's Carole ;)

**Comment by nakajima** [comment]
:+1: ;)

**Comment by baffers** [comment]
💣

**Pull request closed without merging**
